import React from 'react'
import Icon from './icon'

function Play(props){
    return(
        // Generated by IcoMoon.io
        //uso spread operator y le heredo a Icon las propiedades recibidas desde Playlist
        <Icon {...props}> 
            <path d="M6 4l20 12-20 12z"></path>      
        </Icon>
    )
}
export default Play